### ISSUE TITLE
Не відображається випадаючий список міст

### ISSUE THREAD

**Issue by ghost** [PerspectiveTeam/NovaposhtaShipping#5]
Для перевірки встановив на чисту мадженту 2.4.6-p5.
На чекауті немає випадаючого списку міст.
![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/170711331/c936e7a3-dbd1-4196-a4b7-97a129c2045f)

**Comment by miartius** [comment]
Помилки в консолі браузера відсутні.

**Comment by monteshot** [comment]
@miartius Підкажіть такі прекондішени:
- Чи було оновлено довідники (див. https://github.com/PerspectiveTeam/NovaposhtaCatalog)
- Чи валідний ключ(чи обраний ключ має тип "Бізнес кабінет", ане не "Мобільний додаток")?
- Чи є хоч одне місто відправки? 
![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/2836146/90dc91cf-61a7-4ecf-a8e6-a920b81b93bb)
- Чи увімкнена хоч одна Делівері технологія?
![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/2836146/2d093122-2e3d-42ea-9f38-41bbc322c493)

**Comment by miartius** [comment]
> @miartius Підкажіть такі прекондішени:
> 
> * Чи було оновлено довідники (див. https://github.com/PerspectiveTeam/NovaposhtaCatalog)
> * Чи валідний ключ(чи обраний ключ має тип "Бізнес кабінет", ане не "Мобільний додаток")?
> * Чи є хоч одне місто відправки?
> * Чи увімкнена хоч одна Делівері технологія?

* Так, довідники всі оновлені.
* Ключ валідний, брався з бізнес кабінету.
* Місто відправки обрано
* Обрані делівері склад-склад, склад-двері.

**Comment by miartius** [comment]
Якщо ввести вручну назву міста, та заповнити всі поля та оновити сторінку випадаючий список з'явиляється та можна вибрати метод доставки.

![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/170711331/579e0e25-6527-4d5c-9205-d811caf45815)

**Comment by artmouse** [comment]
Перевірив у себе - також немає...

![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/527232/fc247214-66df-4bfb-abe2-bcc7ef3015dc)

**Comment by artmouse** [comment]
Ось така помилка присутня доки не введений e-mail

![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/527232/d8407e52-00af-40b8-b375-e435c0f423f9)

![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/527232/8a4b382a-687a-443f-93ec-46fa577469fe)

**Comment by artmouse** [comment]
![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/527232/49d6d7f6-25ae-4c10-baa3-ff601b9b7209)

![image](https://github.com/PerspectiveTeam/NovaposhtaShipping/assets/527232/21f66924-8efb-438b-813d-3d63c0334576)

**Comment by artmouse** [comment]
Тобто виходить що поки не вибраний selectedMethodCode то місто не відображається.
https://github.com/PerspectiveTeam/NovaposhtaShipping/blob/316ce98eb2dab8aea22da746650cf081cc01b6f3/view/frontend/web/template/checkout/shipping/city.html#L1

**Comment by sydor-dev** [comment]
Помилка з логів
```
Error: Object Perspective\NovaposhtaShipping\Model\Box\LimitedSupplyTestBox#3766 not contained in WeakMap in /var/www/html/vendor/dvdoug/boxpacker/src/Packer.php:327
Stack trace:
#0 /var/www/html/vendor/dvdoug/boxpacker/src/Packer.php(201): DVDoug\BoxPacker\Packer->getBoxList(false)
#1 /var/www/html/vendor/dvdoug/boxpacker/src/Packer.php(175): DVDoug\BoxPacker\Packer->doBasicPacking()
#2 /var/www/html/app/code/Perspective/NovaposhtaShipping/Helper/Boxpacker.php(153): DVDoug\BoxPacker\Packer->pack()
#3 /var/www/html/app/code/Perspective/NovaposhtaShipping/Helper/NovaposhtaHelper.php(182): Perspective\NovaposhtaShipping\Helper\Boxpacker->calcSeats(Array)
#4 /var/www/html/app/code/Perspective/NovaposhtaShipping/Model/Carrier/NovaposhtaShipping.php(209): Perspective\NovaposhtaShipping\Helper\NovaposhtaHelper->getShippingPriceByData(Array)
#5 /var/www/html/vendor/magento/module-shipping/Model/Shipping.php(335): Perspective\NovaposhtaShipping\Model\Carrier\NovaposhtaShipping->collectRates(Object(Magento\Quote\Model\Quote\Address\RateRequest))
...
```

<img width="1408" height="425" alt="Image" src="https://github.com/user-attachments/assets/253f42f4-3e78-4e11-8e8e-b63857c4ff15" />

Природа та сама, що і для https://github.com/PerspectiveTeam/NovaposhtaShipping/issues/12
А саме: при вводі адреси виконується /V1/carts/mine/estimate-shipping-method на Бек і collectRates() падає для  NovaposhtaShipping
Має бути пофікшено в рамках https://github.com/PerspectiveTeam/NovaposhtaShipping/issues/12

**Comment by sydor-dev** [comment]
Помилка з логів
```
Error: Object Perspective\NovaposhtaShipping\Model\Box\LimitedSupplyTestBox#3766 not contained in WeakMap in /var/www/html/vendor/dvdoug/boxpacker/src/Packer.php:327
Stack trace:
#0 /var/www/html/vendor/dvdoug/boxpacker/src/Packer.php(201): DVDoug\BoxPacker\Packer->getBoxList(false)
#1 /var/www/html/vendor/dvdoug/boxpacker/src/Packer.php(175): DVDoug\BoxPacker\Packer->doBasicPacking()
#2 /var/www/html/app/code/Perspective/NovaposhtaShipping/Helper/Boxpacker.php(153): DVDoug\BoxPacker\Packer->pack()
#3 /var/www/html/app/code/Perspective/NovaposhtaShipping/Helper/NovaposhtaHelper.php(182): Perspective\NovaposhtaShipping\Helper\Boxpacker->calcSeats(Array)
#4 /var/www/html/app/code/Perspective/NovaposhtaShipping/Model/Carrier/NovaposhtaShipping.php(209): Perspective\NovaposhtaShipping\Helper\NovaposhtaHelper->getShippingPriceByData(Array)
#5 /var/www/html/vendor/magento/module-shipping/Model/Shipping.php(335): Perspective\NovaposhtaShipping\Model\Carrier\NovaposhtaShipping->collectRates(Object(Magento\Quote\Model\Quote\Address\RateRequest))
...
```

<img width="1113" height="368" alt="Image" src="https://github.com/user-attachments/assets/06821c45-651d-48ea-82ff-0722b10e6c18" />

Природа та сама, що і для https://github.com/PerspectiveTeam/NovaposhtaShipping/issues/12
А саме: при вводі адреси виконується /V1/carts/mine/estimate-shipping-methods на Бек і collectRates() падає для  NovaposhtaShipping
При цьому поле з автокомплітом відображається при виборі доставки НП, інакше - звичайне поле

Має бути пофікшено в рамках https://github.com/PerspectiveTeam/NovaposhtaShipping/issues/12

**Comment by monteshot** [comment]
Виглядає, що ПР https://github.com/PerspectiveTeam/NovaposhtaShipping/pull/13 допоміг.

@artmouse, перевірте, плз, чи відтворюєтся у вас.
Наразі, закриваю issue,
